### PR TITLE
feat: from id to querySelector

### PR DESCRIPTION
**Pull request by Cadienvan**
As mentioned in our chat this would greatly improve DX allowing template usage in different contexts where an id can't be taken for granted!

### CODE REVIEW

**Comment by retrohacker** [comment]
Hey @Cadienvan - sorry for the delay have been on vacation.

Mind refreshing my memory (and, in doing so, documenting here in the repo) what contexts an ID can't be taken for granted?

Since we are querying off `document`, doesn't the `<template>` need to have a unique identifier to reliably grab it from the DOM?

**Comment by Cadienvan** [comment]
Let's imagine multiple templates generated server side which can rely on a class or a data attribute instead of an id. In that case we would force the Dev to bring in some IDs just for the purpose of making it work.

Another case, remotely applicable but still present, could be a WYSIWYG in where a backoffice person could add a template tag and see it powered in frontend. That would need a query selector because we can't expect a non-dev to be knowledgeable about the topic

**Comment by retrohacker** [comment]
I'm going to keep this PR in the back of my mind and save it for a "let's cross that bridge when we get there" day.

I personally like the idea of forcing `<template>`s to use `id` in the codebases since they really should be unique.

I can see a world where we support dependencies, at which point we might switch to classes to allow for nesting templates as a form of "scoping" or something (is that even possible? IDK, haven't tried!)

But we can design for these use cases as we stub our toes on them.

**Comment by retrohacker** [comment]
As an aside, unrelated to this PR, have you experimented with 2-way data binding with your library and Template yet?

That seemed like a pretty cool pattern.

**Comment by Cadienvan** [comment]
> As an aside, unrelated to this PR, have you experimented with 2-way data binding with your library and Template yet?
> 
> That seemed like a pretty cool pattern.

I'm still investigating into it, as how my signal is implemented it shouldn't be THAT hard to do that, I just need to correctly reason about raw signal setters and the rendering function!

What about you?

**Pull request closed without merging**
